In [ ]:
import numpy as np
import tensorflow
from sklearn.metrics import accuracy_score
#from tensorflow import set_random_seed
from keras.models import load_model
from keras.layers import Input, Embedding, LSTM, Dense,Concatenate,Lambda
from keras.models import Model
import keras
from keras import backend as K
from keras.layers import Dense, Activation, Flatten,TimeDistributed,Dropout,Bidirectional
from keras.layers import RepeatVector,merge,Permute,GlobalMaxPool1D
#from attention_utils import get_activations, get_data_recurrent
from keras.callbacks import EarlyStopping
import _pickle as cPickle
np.random.seed(123)
tensorflow.random.set_seed(2)
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import requests

In [ ]:
df_newfile=pd.read_csv("/content/new_file (2).csv")
df_newfile.head()

Country  Slow  Moderate  Fast
0        Aruba     0         2     1
1  Afghanistan     0         2     1
2       Angola     0         2     1
3      Albania     0         1     2
4      Andorra     1         0     2

In [ ]:
# create an Empty DataFrame
df_train = pd.DataFrame(columns = ['SN', 'Date', 'Confirmed Cases','Daily Cases','Country']) 

for ind in df_newfile.index:
  countryname=df_newfile['Country'][ind]
  slowphase=df_newfile['Slow'][ind]
  #df_slow stores SN, Date, ConfirmedCases
  dfslow=pd.read_csv('/content/'+countryname+'.csv_split'+str(slowphase)+'.csv')
  #we add a column with country name and another one with daily cases
  dfslow['CountryName']=countryname
  dfslow['Daily Cases'] = dfslow['Confirmed Cases'].diff().fillna(0)
  
  if (countryname=='Japan' or countryname=='India' or countryname=='Indonesia' or countryname=='United States' or countryname=='Brazil'):
    dfslow=dfslow[0:len(dfslow.index)-17]
  
  #now we add this to Train data set
  for ind2 in dfslow.index:
    df_train = df_train.append({'SN' :dfslow['SN'][ind2],'Date':dfslow['Date'][ind2], 'Confirmed Cases' :dfslow['Confirmed Cases'][ind2],'Daily Cases':dfslow['Daily Cases'][ind2],'Country':countryname}, ignore_index = True)
  #df_train.append(dfslow, ignore_index=True)
  #del dfslow


print(df_train)



FileNotFoundError: ignored

In [ ]:
df_train.to_csv('df_train.csv')

In [ ]:
X_train=[]
Y_train=[]

#now we divide df_train to X_train and Y_train

#for every country in df_newfile
for ind in df_newfile.index:
  countryname=df_newfile['Country'][ind]
  
  for ind2 in dfslow.index:
    df_g=df_train[df_train['Country']==countryname]
    df_g = df_g[df_g['Daily Cases']>0]
    df_g=df_g['Daily Cases']
    data=df_g.values
    for i in range(0,len(data)):
        if i+17<=len(data):
            X_train.append(data[i:i+10])
            Y_train.append(data[i+10:i+17])
    
X_train=np.array(X_train)
Y_train=np.array(Y_train)
print(X_train)
print(Y_train)
print(len(X_train))
print(len(Y_train))

[[2.000e+00 1.000e+00 1.000e+00 ... 1.100e+01 5.000e+00 1.300e+01]
 [1.000e+00 1.000e+00 1.000e+00 ... 5.000e+00 1.300e+01 4.000e+00]
 [1.000e+00 1.000e+00 4.000e+00 ... 1.300e+01 4.000e+00 5.000e+00]
 ...
 [9.880e+02 1.218e+03 1.240e+03 ... 1.837e+03 1.727e+03 1.716e+03]
 [1.218e+03 1.240e+03 1.032e+03 ... 1.727e+03 1.716e+03 1.674e+03]
 [1.240e+03 1.032e+03 6.490e+02 ... 1.716e+03 1.674e+03 1.455e+03]]
[[4.000e+00 5.000e+00 5.000e+00 ... 2.000e+00 7.000e+00 3.000e+00]
 [5.000e+00 5.000e+00 2.000e+00 ... 7.000e+00 3.000e+00 3.000e+00]
 [5.000e+00 2.000e+00 2.000e+00 ... 3.000e+00 3.000e+00 5.000e+00]
 ...
 [1.674e+03 1.455e+03 1.713e+03 ... 2.642e+03 2.539e+03 2.312e+03]
 [1.455e+03 1.713e+03 3.267e+03 ... 2.539e+03 2.312e+03 2.594e+03]
 [1.713e+03 3.267e+03 2.642e+03 ... 2.312e+03 2.594e+03 2.112e+03]]
2828000
2828000


In [ ]:
#scaling the data
scaler = MinMaxScaler(feature_range=(0, 1))
data=df_train['Confirmed Cases'].values
#print(data.shape)
data=data.reshape((len(data),1))
scaler.fit(data)
X_train= scaler.transform(X_train)
Y_train=scaler.transform(Y_train)

X_train=X_train.reshape((len(X_train),10,1))
print(X_train.shape,Y_train.shape)


(2828000, 10, 1) (2828000, 7)


In [ ]:
# LSTM architecture
def model_arch():
    lstm_hidden = 32
    initi = keras.initializers.RandomNormal(mean=0.0, stddev=0.01, seed=123)
    main_input = Input(shape=(10,1), name='main_input')
    lstm_out = LSTM(lstm_hidden,kernel_initializer=initi, recurrent_initializer= initi, bias_initializer=initi)(main_input)
    lstm_out = Dropout(0.45)(lstm_out)
    main_output = (Dense(7, name='main_output')(lstm_out))
#     Adam=keras.optimizers.Adam(lr=0.01, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.01, amsgrad=False)

    model = Model(inputs=main_input, outputs=main_output)
    model.compile(loss='mean_squared_error',optimizer='adam')
    return model

model = model_arch()
earlystop=EarlyStopping(monitor='val_acc', min_delta=0, patience=4, verbose=0, mode='auto', baseline=None, restore_best_weights=True)
callbacks_list = [earlystop]
print("model is building")
bs = 128
model.fit(batch_size=bs,epochs=10,x=X_train,y=Y_train, verbose=1,validation_split=0.1)
print("model building done")
    

model is building
Epoch 1/10
19885/19885 [==============================] - 118s 6ms/step - loss: 4.0749e-04 - val_loss: 9.1614e-07
Epoch 2/10
19885/19885 [==============================] - 118s 6ms/step - loss: 2.9702e-04 - val_loss: 1.2097e-06
Epoch 3/10
19885/19885 [==============================] - 116s 6ms/step - loss: 2.6217e-04 - val_loss: 8.7506e-07
Epoch 4/10
19885/19885 [==============================] - 116s 6ms/step - loss: 2.5382e-04 - val_loss: 8.7561e-07
Epoch 5/10
19885/19885 [==============================] - 116s 6ms/step - loss: 2.4679e-04 - val_loss: 3.2373e-07
Epoch 6/10
19885/19885 [==============================] - 116s 6ms/step - loss: 2.4175e-04 - val_loss: 5.2944e-07
Epoch 7/10
19885/19885 [==============================] - 116s 6ms/step - loss: 2.4224e-04 - val_loss: 6.7808e-07
Epoch 8/10
19885/19885 [==============================] - 117s 6ms/step - loss: 2.4051e-04 - val_loss: 2.0543e-06
Epoch 9/10
19885/19885 [==============================] - 117s 6ms/ste

In [ ]:
# Prepare test data
X_test=[]
Y_test=[]
for ind in df_newfile.index:
  countryname=df_newfile['Country'][ind]
  slowphase=df_newfile['Slow'][ind]
  #df_slow stores SN, Date, ConfirmedCases
  df2=pd.read_csv('/content/'+countryname+'.csv_split'+str(slowphase)+'.csv')
  #we add a column with country name and another one with daily cases
  df2['CountryName']=countryname
  df2['Daily Cases'] = df2['Confirmed Cases'].diff().fillna(0)
  
  if (countryname=='Japan' or countryname=='India' or countryname=='Indonesia' or countryname=='United States' or countryname=='Brazil'):
    df2=df2[len(df2.index)-1-17:len(df2.index)]
    df2 = df2[df2['Daily Cases']>0]
    df3=df2['Daily Cases']
    data2=df3.values
    #print(len(data2),"\n")
    for i in range(0,len(data2)):
        if i+17<=len(data2):
            X_test.append(data2[i:i+10])
            Y_test.append(data2[i+10:i+17])


X_test=np.array(X_test)
Y_test=np.array(Y_test)
print(len(X_test),len(Y_test))

7 7


In [ ]:
X_test= scaler.transform(X_test)
X_test=X_test.reshape((len(X_test),10,1))
print(X_test.shape,Y_test.shape)

(7, 10, 1) (7, 7)


In [ ]:
# prediction
pred=model.predict(x=X_test)
print(pred.shape)
#inverse scaling
pred1=scaler.inverse_transform(pred)

#Find RMSE
from sklearn.metrics import mean_squared_error

rms = mean_squared_error(Y_test, pred1)
print(np.sqrt(rms))

(7, 7)
6829.015779286535
